version: "3"
services:
  opensearch:
    image: opensearchproject/opensearch
    ports:
      - 9200:9200
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    environment:
      discovery.type: single-node
      plugins.security.disabled: true # 認証とSSLを無効化

volumes:
  opensearch-data:
